name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v1
        
        - name: Use Node.js 12.x
          uses: actions/setup-node@v1
          with:
            node-version: 12.x
        - run: npm install
          working-directory: blog
        - run: npm run build --if-present
          working-directory: blog

        - name: Publish
          uses: netlify/actions/cli@master
          with:
            args: deploy --dir=blog/public --prod
          env:
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}


          